//! Static HTML: readable with JavaScript off, from `file://`, in a
//! terminal browser. There is no script tag anywhere in the output and
//! there never will be — documentation that needs a runtime to be read
//! is documentation that stops working.
//!
//! The markdown subset rendered here is deliberately small and
//! deterministic: paragraphs, fenced code, headings, bullet lists,
//! inline `code`, `**bold**`, `*italic*`, and intra-doc links. Anything
//! else passes through escaped, which is the honest failure mode — a
//! reader sees the source text rather than a mangled page.

use wolf_query::{Directive, DocComment, DocFence, DocModule, DocPackage};

use crate::{Options, module_label, vis_word};

pub const STYLE: &str = "\
/* wolf doc — no JavaScript, no web fonts, no network. */\n\
:root { --fg: #1b1b1b; --bg: #fdfdfd; --dim: #5a5a5a; --rule: #d8d8d8;\n\
        --code: #f4f4f2; --link: #21507a; }\n\
@media (prefers-color-scheme: dark) {\n\
  :root { --fg: #e6e6e6; --bg: #16181a; --dim: #a0a4a8; --rule: #33383c;\n\
          --code: #1e2225; --link: #8ab4e8; }\n\
}\n\
* { box-sizing: border-box; }\n\
body { margin: 0 auto; padding: 2rem 1.25rem 6rem; max-width: 46rem;\n\
       color: var(--fg); background: var(--bg); line-height: 1.55;\n\
       font-family: ui-serif, Georgia, 'Times New Roman', serif; }\n\
code, pre, .sig { font-family: ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace;\n\
                  font-size: 0.9em; }\n\
a { color: var(--link); }\n\
h1 { font-size: 1.6rem; margin: 0 0 0.25rem; }\n\
h2 { font-size: 1.2rem; margin: 2.5rem 0 0.5rem; border-bottom: 1px solid var(--rule);\n\
     padding-bottom: 0.25rem; }\n\
h3 { font-size: 1rem; margin: 2rem 0 0.35rem; }\n\
.crumb, .meta { color: var(--dim); font-size: 0.85rem; }\n\
.sig { display: block; white-space: pre-wrap; overflow-x: auto; background: var(--code);\n\
       border-left: 3px solid var(--rule); padding: 0.5rem 0.7rem; margin: 0.35rem 0 0.6rem; }\n\
pre { background: var(--code); padding: 0.7rem 0.8rem; overflow-x: auto;\n\
      border-radius: 3px; }\n\
pre.doctest { border-left: 3px solid var(--link); }\n\
.tag { display: inline-block; font-size: 0.72rem; letter-spacing: 0.04em;\n\
       text-transform: uppercase; color: var(--dim); border: 1px solid var(--rule);\n\
       border-radius: 2px; padding: 0 0.3rem; margin-left: 0.35rem; vertical-align: 0.1em; }\n\
table { border-collapse: collapse; width: 100%; display: block; overflow-x: auto; }\n\
td, th { text-align: left; padding: 0.3rem 0.6rem 0.3rem 0; border-bottom: 1px solid var(--rule);\n\
         vertical-align: top; }\n\
.item { margin-bottom: 1.6rem; }\n\
.broken { color: #a33; text-decoration: underline dotted; }\n\
footer { margin-top: 4rem; border-top: 1px solid var(--rule); padding-top: 0.8rem; }\n";

/// HTML-escape text (also used by the JSON writer's prose).
pub fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}

/// The file name of a module's page. The root module is `module.html`;
/// nested modules dot-join, so a page name never contains a separator
/// and the site is one flat directory (a flat directory copies, serves
/// and diffs without surprises).
pub fn module_page_name(path: &str) -> String {
    if path.is_empty() {
        "module.html".to_string()
    } else {
        format!("module.{path}.html")
    }
}

fn page(title: &str, body: &str) -> Vec<u8> {
    format!(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <meta name=\"generator\" content=\"wolf doc\">\n\
         <title>{}</title>\n<link rel=\"stylesheet\" href=\"style.css\">\n\
         </head>\n<body>\n{body}<footer class=\"meta\">Generated by <code>wolf doc</code> \
         from doc comments and the compiler&rsquo;s own signatures. \
         Every signature on this page is the one the compiler resolved; \
         no part of it was re-parsed from source.</footer>\n</body>\n</html>\n",
        escape(title)
    )
    .into_bytes()
}

/// The index page: the module list with summaries, plus the resolved
/// dependency surface this documentation was generated against.
pub fn index(docs: &DocPackage, opts: &Options, title: &str) -> Vec<u8> {
    let mut b = String::new();
    b.push_str(&format!("<h1>{}</h1>\n", escape(title)));
    b.push_str(&format!(
        "<p class=\"meta\">{} module{} · {} documented item{}{}</p>\n",
        docs.modules.len(),
        plural(docs.modules.len()),
        docs.items().count(),
        plural(docs.items().count()),
        if docs.private {
            " · private items included"
        } else {
            ""
        }
    ));
    b.push_str("<h2>Modules</h2>\n<table>\n");
    for m in &docs.modules {
        b.push_str(&format!(
            "<tr><td><a href=\"{}\"><code>{}</code></a></td><td>{}</td></tr>\n",
            escape(&module_page_name(&m.path)),
            escape(&module_label(&m.path)),
            m.doc
                .as_ref()
                .map(|d| inline(&d.summary, docs))
                .unwrap_or_default()
        ));
    }
    b.push_str("</table>\n");
    if !opts.deps.is_empty() {
        b.push_str(
            "<h2>Documented against</h2>\n<p class=\"meta\">The resolved dependency set \
             this documentation describes. A different resolution documents a different \
             world, so it is recorded here and in <code>index.json</code>.</p>\n<table>\n\
             <tr><th>alias</th><th>package</th><th>version</th></tr>\n",
        );
        for (alias, name, version) in &opts.deps {
            b.push_str(&format!(
                "<tr><td><code>{}</code></td><td>{}</td><td><code>{}</code></td></tr>\n",
                escape(alias),
                escape(name),
                escape(version)
            ));
        }
        b.push_str("</table>\n");
    }
    page(title, &b)
}

/// One module's page: its `//!` prose, then every item with its
/// signature, its docs and its doctests.
pub fn module_page(docs: &DocPackage, module: &DocModule, _opts: &Options, title: &str) -> Vec<u8> {
    let label = module_label(&module.path);
    let mut b = String::new();
    b.push_str(&format!(
        "<p class=\"crumb\"><a href=\"index.html\">{}</a> / <code>{}</code></p>\n",
        escape(title),
        escape(&label)
    ));
    b.push_str(&format!("<h1><code>{}</code></h1>\n", escape(&label)));
    if let Some(d) = &module.doc {
        b.push_str(&markdown(d, docs));
    }
    if module.items.is_empty() {
        b.push_str("<p class=\"meta\">This module exports nothing.</p>\n");
        return page(&format!("{label} — {title}"), &b);
    }
    // The listing: summary lines, then the full entries.
    b.push_str("<h2>Items</h2>\n<table>\n");
    for item in &module.items {
        b.push_str(&format!(
            "<tr><td><a href=\"#{}\"><code>{}</code></a></td><td>{}</td></tr>\n",
            escape(&anchor(&item.name)),
            escape(&item.name),
            item.doc
                .as_ref()
                .map(|d| inline(&d.summary, docs))
                .unwrap_or_default()
        ));
    }
    b.push_str("</table>\n");
    for item in &module.items {
        b.push_str(&format!(
            "<div class=\"item\">\n<h3 id=\"{}\"><code>{}</code>\
             <span class=\"tag\">{}</span><span class=\"tag\">{}</span></h3>\n",
            escape(&anchor(&item.name)),
            escape(&item.name),
            escape(item.kind.keyword()),
            escape(vis_word(item))
        ));
        b.push_str(&format!(
            "<code class=\"sig\">{}</code>\n",
            escape(&item.sig)
        ));
        match &item.doc {
            Some(d) => b.push_str(&markdown(d, docs)),
            None => b.push_str(
                "<p class=\"meta\">Undocumented. (This item has no doc comment; \
                 the coverage report names it.)</p>\n",
            ),
        }
        b.push_str("</div>\n");
    }
    page(&format!("{label} — {title}"), &b)
}

fn plural(n: usize) -> &'static str {
    if n == 1 { "" } else { "s" }
}

fn anchor(name: &str) -> String {
    let mut out = String::from("item.");
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' || c == '.' {
            out.push(c);
        } else {
            out.push('-');
        }
    }
    out
}

/// The markdown subset. Deterministic, escaping by default.
fn markdown(doc: &DocComment, docs: &DocPackage) -> String {
    let mut out = String::new();
    let mut para: Vec<&str> = Vec::new();
    let mut list: Vec<String> = Vec::new();
    let mut fence: Option<(usize, Vec<&str>)> = None;
    let mut fence_n = 0usize;
    let flush_para = |out: &mut String, para: &mut Vec<&str>| {
        if para.is_empty() {
            return;
        }
        out.push_str(&format!("<p>{}</p>\n", inline(&para.join(" "), docs)));
        para.clear();
    };
    let flush_list = |out: &mut String, list: &mut Vec<String>| {
        if list.is_empty() {
            return;
        }
        out.push_str("<ul>\n");
        for item in list.iter() {
            out.push_str(&format!("<li>{}</li>\n", inline(item, docs)));
        }
        out.push_str("</ul>\n");
        list.clear();
    };
    for line in doc.text.lines() {
        let t = line.trim_end();
        let trimmed = t.trim_start();
        if let Some((idx, body)) = fence.as_mut() {
            if trimmed.starts_with("```") {
                let f = doc.fences.get(*idx);
                out.push_str(&render_fence(f, body));
                fence = None;
            } else {
                body.push(t);
            }
            continue;
        }
        if trimmed.starts_with("```") {
            flush_para(&mut out, &mut para);
            flush_list(&mut out, &mut list);
            fence = Some((fence_n, Vec::new()));
            fence_n += 1;
            continue;
        }
        if trimmed.is_empty() {
            flush_para(&mut out, &mut para);
            flush_list(&mut out, &mut list);
            continue;
        }
        if let Some(rest) = trimmed
            .strip_prefix("- ")
            .or_else(|| trimmed.strip_prefix("* "))
        {
            flush_para(&mut out, &mut para);
            list.push(rest.to_string());
            continue;
        }
        if let Some(last) = list.last_mut() {
            // A continuation line of the current bullet.
            last.push(' ');
            last.push_str(trimmed);
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("### ") {
            flush_para(&mut out, &mut para);
            out.push_str(&format!("<h4>{}</h4>\n", inline(rest, docs)));
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("## ") {
            flush_para(&mut out, &mut para);
            out.push_str(&format!("<h4>{}</h4>\n", inline(rest, docs)));
            continue;
        }
        para.push(trimmed);
    }
    flush_para(&mut out, &mut para);
    flush_list(&mut out, &mut list);
    if let Some((idx, body)) = fence {
        out.push_str(&render_fence(doc.fences.get(idx), &body));
    }
    out
}

fn render_fence(f: Option<&DocFence>, body: &[&str]) -> String {
    let code = escape(&body.join("\n"));
    let Some(f) = f else {
        return format!("<pre><code>{code}</code></pre>\n");
    };
    if !f.is_example() {
        return format!("<pre><code>{code}</code></pre>\n");
    }
    let mut tags = String::new();
    // An example this toolchain does not execute says so on the page.
    if !f.is_doctest() {
        tags.push_str(&format!(
            "<span class=\"tag\">{} example, run by its own rig</span>",
            escape(&f.lang)
        ));
    }
    for d in &f.directives {
        let text = match d {
            Directive::NoRun => "compiled, not run".to_string(),
            Directive::Ignore => "not compiled".to_string(),
            Directive::ShouldFail(codes) if codes.is_empty() => "must be refused".to_string(),
            Directive::ShouldFail(codes) => format!("must be refused: {}", codes.join(", ")),
        };
        tags.push_str(&format!("<span class=\"tag\">{}</span>", escape(&text)));
    }
    format!(
        "<p class=\"meta\">doctest{tags}</p>\n<pre class=\"doctest\"><code>{code}</code></pre>\n"
    )
}

/// Inline markup: `code`, `**bold**`, `*italic*`, `[intra.doc.links]`.
fn inline(s: &str, docs: &DocPackage) -> String {
    let mut out = String::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'`' => {
                if let Some(end) = s[i + 1..].find('`') {
                    out.push_str(&format!("<code>{}</code>", escape(&s[i + 1..i + 1 + end])));
                    i += end + 2;
                    continue;
                }
                out.push_str("&#96;");
                i += 1;
            }
            b'*' if s[i..].starts_with("**") => {
                if let Some(end) = s[i + 2..].find("**") {
                    out.push_str(&format!(
                        "<strong>{}</strong>",
                        inline(&s[i + 2..i + 2 + end], docs)
                    ));
                    i += end + 4;
                    continue;
                }
                out.push_str("**");
                i += 2;
            }
            b'*' => {
                if let Some(end) = s[i + 1..].find('*') {
                    out.push_str(&format!(
                        "<em>{}</em>",
                        inline(&s[i + 1..i + 1 + end], docs)
                    ));
                    i += end + 2;
                    continue;
                }
                out.push('*');
                i += 1;
            }
            b'[' => {
                let Some(end) = s[i + 1..].find(']') else {
                    out.push_str("&#91;");
                    i += 1;
                    continue;
                };
                let target = &s[i + 1..i + 1 + end];
                let after = s[i + 1 + end + 1..].chars().next();
                if after == Some('(') {
                    // An ordinary markdown link: keep its text, drop the
                    // URL — an external URL in generated docs is a
                    // dangling promise we do not make.
                    out.push_str(&inline(target, docs));
                    let rest = &s[i + 1 + end + 1..];
                    let close = rest.find(')').map(|p| p + 1).unwrap_or(rest.len());
                    i += end + 2 + close;
                    continue;
                }
                out.push_str(&link(target, docs));
                i += end + 2;
            }
            _ => {
                let ch = s[i..].chars().next().unwrap_or('?');
                out.push_str(&escape(&ch.to_string()));
                i += ch.len_utf8();
            }
        }
    }
    out
}

/// Render an intra-doc link. A resolvable target becomes an anchor into
/// the generated site; an unresolvable one is marked, not hidden — the
/// page tells the truth and W1501 already said it on the build.
fn link(target: &str, docs: &DocPackage) -> String {
    let bare = target.strip_suffix("()").unwrap_or(target);
    // `module.item`, then `item` in any module, then a module path.
    for m in &docs.modules {
        for it in &m.items {
            let qualified = if m.path.is_empty() {
                it.name.clone()
            } else {
                format!("{}.{}", m.path, it.name)
            };
            let short = m
                .path
                .rsplit('.')
                .next()
                .map(|last| format!("{last}.{}", it.name));
            if bare == qualified || bare == it.name || short.as_deref() == Some(bare) {
                return format!(
                    "<a href=\"{}#{}\"><code>{}</code></a>",
                    escape(&module_page_name(&m.path)),
                    escape(&anchor(&it.name)),
                    escape(target)
                );
            }
        }
    }
    for m in &docs.modules {
        if !m.path.is_empty() && (bare == m.path || Some(bare) == m.path.rsplit('.').next()) {
            return format!(
                "<a href=\"{}\"><code>{}</code></a>",
                escape(&module_page_name(&m.path)),
                escape(target)
            );
        }
    }
    // A `Type.member` link whose head resolves points at the type.
    if let Some((head, _)) = bare.split_once('.') {
        for m in &docs.modules {
            for it in &m.items {
                if it.name == head {
                    return format!(
                        "<a href=\"{}#{}\"><code>{}</code></a>",
                        escape(&module_page_name(&m.path)),
                        escape(&anchor(&it.name)),
                        escape(target)
                    );
                }
            }
        }
    }
    format!("<code class=\"broken\">{}</code>", escape(target))
}
