//! Spec extraction (s03): ```ebnf fenced blocks in spec documents are the
//! normative grammar; extraction concatenates them (in document order)
//! into `spec/grammar.ebnf`. CI runs `spec-extract --check` so the doc and
//! the extracted file can never drift.

/// Extract all ```ebnf fenced blocks from markdown, in order.
pub fn extract_ebnf(md: &str) -> String {
    let mut out = String::from(
        "# GENERATED by `cargo xtask spec-extract` from spec/01-grammar.md — do not edit.\n",
    );
    let mut in_block = false;
    for line in md.lines() {
        let trimmed = line.trim_end();
        if in_block {
            if trimmed == "```" {
                in_block = false;
                out.push('\n');
            } else {
                out.push_str(trimmed);
                out.push('\n');
            }
        } else if trimmed == "```ebnf" {
            in_block = true;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_in_order_and_ignores_other_fences() {
        let md =
            "a\n```ebnf\nA ::= 'x'\n```\nprose\n```text\nnot grammar\n```\n```ebnf\nB ::= A\n```\n";
        let got = extract_ebnf(md);
        assert!(got.contains("A ::= 'x'"));
        assert!(got.contains("B ::= A"));
        assert!(!got.contains("not grammar"));
        let a = got.find("A ::=").unwrap();
        let b = got.find("B ::=").unwrap();
        assert!(a < b);
    }
}
