//! Spec extraction (s03): ```ebnf fenced blocks in spec documents are the
//! normative grammar; extraction concatenates them (in document order)
//! into `spec/grammar.ebnf`. CI runs `spec-extract --check` so the doc and
//! the extracted file can never drift. The §3.2 precedence climb
//! (`[gram.expr.prec]`) lives in the spec as a table, not a fence;
//! extraction renders it into EBNF productions (s21 side task) so the
//! emitted grammar carries the full operator inventory with its tiers.

/// Extract all ```ebnf fenced blocks from markdown, in order, plus the
/// deterministic rendering of the `[gram.expr.prec]` climb table at its
/// document position.
pub fn extract_ebnf(md: &str) -> String {
    let mut out = String::from(
        "# GENERATED by `cargo xtask spec-extract` from spec/01-grammar.md — do not edit.\n",
    );
    let mut in_block = false;
    // Climb-table scanner: armed by the [gram.expr.prec] heading,
    // collects the first markdown table that follows, renders it once.
    let mut prec_armed = false;
    let mut prec_rows: Vec<String> = Vec::new();
    let mut prec_done = false;
    for line in md.lines() {
        let trimmed = line.trim_end();
        if in_block {
            if trimmed == "```" {
                in_block = false;
                out.push('\n');
            } else {
                out.push_str(trimmed);
                out.push('\n');
            }
            continue;
        }
        if trimmed == "```ebnf" {
            in_block = true;
            continue;
        }
        if !prec_done {
            if trimmed.starts_with('#') && trimmed.contains("[gram.expr.prec]") {
                prec_armed = true;
            } else if prec_armed && trimmed.starts_with('|') {
                prec_rows.push(trimmed.to_string());
            } else if !prec_rows.is_empty() {
                // Table ended: render at this document position.
                out.push_str(&render_climb(&prec_rows));
                out.push('\n');
                prec_done = true;
            }
        }
    }
    out
}

// ------------------------------------------------ precedence climb ----

/// One parsed row of the §3.2 climb table.
struct ClimbTier {
    tier: u32,
    /// The backtick-quoted operator spellings, in table order
    /// (markdown `\|` escapes undone).
    ops: Vec<String>,
    assoc: String,
}

/// Render the `[gram.expr.prec]` table into EBNF. The table is the
/// authority: operator inventories come from its cells; only the
/// production names and climb shapes are fixed here. Panics (with the
/// offending row) if the table stops looking like the climb this
/// renderer understands — the extractor must never silently emit a
/// stale climb.
fn render_climb(rows: &[String]) -> String {
    let tiers: Vec<ClimbTier> = rows.iter().filter_map(|r| parse_climb_row(r)).collect();
    // Production name per tier; `next` is the tighter tier it climbs
    // from. Tiers 1/2/14/15 are spelled in [gram.expr.primary]
    // (`primary`, `postfix_expr`, `range_expr`, `else_expr`).
    let name = |t: u32| -> Option<(&'static str, &'static str)> {
        Some(match t {
            3 => ("prefix_operand", "postfix_expr"),
            4 => ("cast_expr", "prefix_operand"),
            5 => ("mul_expr", "cast_expr"),
            6 => ("add_expr", "mul_expr"),
            7 => ("shift_expr", "add_expr"),
            8 => ("bitand_expr", "shift_expr"),
            9 => ("bitxor_expr", "bitand_expr"),
            10 => ("bitor_expr", "bitxor_expr"),
            11 => ("cmp_expr", "bitor_expr"),
            12 => ("and_expr", "cmp_expr"),
            13 => ("or_expr", "and_expr"),
            _ => return None,
        })
    };
    for expected in 1..=15u32 {
        assert!(
            tiers.iter().any(|t| t.tier == expected),
            "[gram.expr.prec] climb table: tier {expected} missing — \
             renderer and spec table have drifted"
        );
    }
    let mut out = String::from(
        "/* [gram.expr.prec] — the authoritative climb, tightest first,\n   \
         rendered from the §3.2 table by `cargo xtask spec-extract`.\n   \
         Tiers 1/2/14/15 are spelled in [gram.expr.primary]: primary,\n   \
         postfix_expr, range_expr, else_expr. Comparison operators\n   \
         (tier 11) do not chain. */\n",
    );
    for t in &tiers {
        let Some((prod, next)) = name(t.tier) else {
            continue; // tiers 1/2/14/15: covered by existing productions
        };
        assert!(
            !t.ops.is_empty(),
            "[gram.expr.prec] tier {}: no operator spellings found",
            t.tier
        );
        let quoted: Vec<String> = t.ops.iter().map(|o| format!("'{o}'")).collect();
        let line = match (t.tier, t.assoc.as_str()) {
            // Prefix tier: operators repeat, then fall to postfix.
            (3, _) => {
                out.push_str(&format!(
                    "prefix_operand ::= prefix_op prefix_operand | {next}   /* tier 3, prefix */\n"
                ));
                format!("prefix_op ::= {}\n", quoted.join(" | "))
            }
            // `as` casts to a TYPE, not an expression.
            (4, "left") => {
                format!("cast_expr ::= {next} ('as' type)*   /* tier 4, left */\n")
            }
            // Non-chaining comparisons: at most one operator.
            (11, "none") => {
                out.push_str(&format!(
                    "cmp_expr ::= {next} (cmp_op {next})?   /* tier 11, none — no chaining */\n"
                ));
                format!("cmp_op ::= {}\n", quoted.join(" | "))
            }
            (_, "left") => {
                let op = if quoted.len() == 1 {
                    quoted[0].clone()
                } else {
                    format!("({})", quoted.join(" | "))
                };
                format!(
                    "{prod} ::= {next} ({op} {next})*   /* tier {}, left */\n",
                    t.tier
                )
            }
            _ => panic!(
                "[gram.expr.prec] tier {}: unrenderable associativity {:?}",
                t.tier, t.assoc
            ),
        };
        out.push_str(&line);
    }
    out
}

/// Parse one `| # | ops | assoc |` data row; `None` for the header and
/// separator rows.
fn parse_climb_row(row: &str) -> Option<ClimbTier> {
    // Markdown escapes `|` inside cells as `\|`; shelter those before
    // splitting on the cell delimiter.
    const SHELTER: char = '\u{1}';
    let sheltered = row.replace("\\|", &SHELTER.to_string());
    let cells: Vec<String> = sheltered
        .trim_matches('|')
        .split('|')
        .map(|c| c.trim().replace(SHELTER, "|"))
        .collect();
    if cells.len() != 3 {
        return None;
    }
    let tier: u32 = cells[0].parse().ok()?; // header/separator rows fail here
    let mut ops = Vec::new();
    let mut rest = cells[1].as_str();
    while let Some(open) = rest.find('`') {
        let Some(len) = rest[open + 1..].find('`') else {
            break;
        };
        ops.push(rest[open + 1..open + 1 + len].to_string());
        rest = &rest[open + 1 + len + 1..];
    }
    let assoc = match cells[2].as_str() {
        "left" => "left",
        "right" => "right",
        "none" => "none",
        _ => "prefix", // the em-dash rows: tier 1 atoms, tier 3 prefix
    };
    Some(ClimbTier {
        tier,
        ops,
        assoc: assoc.to_string(),
    })
}

/// Cross-reference link pass (s05): every `[prefix.…]` anchor cited in any
/// spec document must exist verbatim in the document that owns the prefix.
/// Ownership map: gram→01, mem→02, conc→03, abi→04.
pub fn link_check(docs: &[(&str, &str)]) -> Vec<String> {
    let owner = |anchor: &str| -> Option<&'static str> {
        let prefix = anchor.split('.').next().unwrap_or("");
        match prefix {
            "gram" => Some("01-grammar.md"),
            "diag" => Some("01-grammar.md"), // §9, the diagnostics tier (s67)
            "mem" => Some("02-memory-model.md"),
            "conc" => Some("03-concurrency.md"),
            "abi" => Some("04-abi.md"),
            "conf" => Some("05-conformance.md"),
            "proto" => Some("06-differential-protocol.md"),
            "pkg" => Some("08-package.md"),
            "ct" => Some("09-constant-time.md"),
            "type" => Some("10-types.md"), // §D54 numeric-literal typing (s113)
            _ => None,                     // corpus-tag namespaces (str.*, err.*, …) are s06's
        }
    };
    let mut errors = Vec::new();
    for (file, body) in docs {
        for anchor in anchors_in(body) {
            let Some(owner_file) = owner(&anchor) else {
                continue;
            };
            let Some((_, owner_body)) = docs.iter().find(|(n, _)| *n == owner_file) else {
                errors.push(format!(
                    "{file}: [{anchor}] cites missing document {owner_file}"
                ));
                continue;
            };
            if !owner_body.contains(&format!("[{anchor}]")) {
                errors.push(format!(
                    "{file}: dangling cross-reference [{anchor}] (not defined in {owner_file})"
                ));
            }
        }
    }
    errors.sort();
    errors.dedup();
    errors
}

/// All `[a.b.c]`-shaped anchors in a document (dotted, lowercase-alnum).
fn anchors_in(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = body.as_bytes();
    let mut i = 0;
    while let Some(open) = body[i..].find('[').map(|o| i + o) {
        let Some(close) = body[open..].find(']').map(|c| open + c) else {
            break;
        };
        let inner = &body[open + 1..close];
        let dotted = inner.contains('.')
            && !inner.contains(' ')
            && inner.chars().all(|c| {
                c.is_ascii_lowercase() || c.is_ascii_digit() || c == '.' || c == '-' || c == '_'
            });
        if dotted {
            out.push(inner.to_string());
        }
        i = close + 1;
        if i >= bytes.len() {
            break;
        }
    }
    out
}

/// Build the anchor registry: every anchor appearing in its OWNING
/// document is a definition ([conf.anchor.index]).
pub fn anchor_index(docs: &[(&str, &str)]) -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    for (file, body) in docs {
        for anchor in anchors_in(body) {
            let prefix = anchor.split('.').next().unwrap_or("");
            let owns = matches!(
                (prefix, *file),
                ("gram", "01-grammar.md")
                    | ("diag", "01-grammar.md")
                    | ("mem", "02-memory-model.md")
                    | ("conc", "03-concurrency.md")
                    | ("abi", "04-abi.md")
                    | ("conf", "05-conformance.md")
                    | ("proto", "06-differential-protocol.md")
                    | ("pkg", "08-package.md")
                    | ("ct", "09-constant-time.md")
                    | ("type", "10-types.md")
            );
            if owns {
                out.insert(anchor, file.to_string());
            }
        }
    }
    out
}

/// Registered namespaces resolve against the anchor index; reserved
/// forward namespaces are legal-but-unresolvable ([conf.anchor.ns]).
pub const REGISTERED_NS: [&str; 9] = [
    "gram", "diag", "mem", "conc", "abi", "conf", "proto", "ct", "type",
];
pub const FORWARD_NS: [&str; 15] = [
    "str", "err", "task", "proc", "sync", "generics", "arith", "ffi", "unsafe", "comptime", "perf",
    "mod", "std", "ty",
    // Appended 2026-08-11 by s39 (the built-in test framework's litmus
    // tier; D34/D36 own the future spec document).
    "test",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_in_order_and_ignores_other_fences() {
        let md =
            "a\n```ebnf\nA ::= 'x'\n```\nprose\n```text\nnot grammar\n```\n```ebnf\nB ::= A\n```\n";
        let got = extract_ebnf(md);
        assert!(got.contains("A ::= 'x'"));
        assert!(got.contains("B ::= A"));
        assert!(!got.contains("not grammar"));
        let a = got.find("A ::=").unwrap();
        let b = got.find("B ::=").unwrap();
        assert!(a < b);
    }

    #[test]
    fn link_check_finds_dangling() {
        let docs = [
            ("02-memory-model.md", "- `[mem.a.1]` rule; see [conc.x.9]."),
            ("03-concurrency.md", "- `[conc.b.2]` rule cites [mem.a.1]."),
        ];
        let errs = link_check(&docs);
        assert_eq!(errs.len(), 1, "{errs:?}");
        assert!(errs[0].contains("conc.x.9"));
    }
}
