[package]
name = "wolf_pkg"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
wolf_span.workspace = true
wolf_diag.workspace = true
wolf_lex.workspace = true
blake3.workspace = true

[dev-dependencies]
insta.workspace = true
